#!/user/bin/bash
node ./ascending_order.js
node ./count_number__below.js
node ./lowest_element_test.js
node ./testForslectEven.js
node ./ascending_order_test.js
node ./count_odd_array_test.js
node ./mapping_length_test.js
node ./testForslectOdd.js
node ./average_of_element_test.js
node ./descending_order_test.js
node ./partition_test.js
node ./testForsumOfArray.js
node ./checkSubset.js
node ./differenceOfArray.js
node ./printing_reverse_test.js
node ./unique_element_test.js
node ./concat_two_array_test.js
node ./exterect_test.js
node ./reverse_fibo_test.js
node ./zipArryTest.js
node ./count_Even_array_test.js
node ./greatest_element_test.js
node ./rotate_array_test.js
node ./count_number__above.js
node ./intersection_of_array_test.js
node ./select_second_element_test.js
